spring:
  jpa:
    defer-datasource-initialization: true  # for initializing data
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always # for initializing data
mysql:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/ddb
    username: user
    password: '1234'
