version: '3'

services:
  db:
    image: mysql:8.0.32
    container_name: ddb-mysql
    volumes:
      - ~/develop/docker-volumes/mysql/video-poker:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: ddb
    ports:
      - '3306:3306'
